# Generated by Django 3.0.3 on 2020-09-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(auto_created=True, default=0)),
                ('url', models.URLField()),
                ('name', models.TextField(unique=True)),
            ],
        ),
    ]
