# Generated by Django 3.0.3 on 2020-09-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20200922_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
